//
//  ProfileInteractor.swift
//  LinkedinClone
//
//  Created by MacOS on 14.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileBusinessLogic {
    func doSomething(request: Profile.Something.Request)
//    func doSomethingElse(request: Profile.SomethingElse.Request)
}

protocol ProfileDataStore {
    //var name: String { get set }
}

class ProfileInteractor: ProfileBusinessLogic, ProfileDataStore {
    var presenter: ProfilePresentationLogic?
    var worker: ProfileWorker?
    //var name: String = ""

    // MARK: Do something (and send response to ProfilePresenter)

    func doSomething(request: Profile.Something.Request) {
        worker = ProfileWorker()
        worker?.doSomeWork()

        let response = Profile.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: Profile.SomethingElse.Request) {
//        worker = ProfileWorker()
//        worker?.doSomeOtherWork()
//
//        let response = Profile.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
