//
//  NetworkPresenter.swift
//  LinkedinClone
//
//  Created by MacOS on 17.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NetworkPresentationLogic {
    func presentSomething(response: Network.Something.Response)
}

class NetworkPresenter: NetworkPresentationLogic {
    weak var viewController: NetworkDisplayLogic?

    // MARK: Parse and calc respnse from NetworkInteractor and send simple view model to NetworkViewController to be displayed

    func presentSomething(response: Network.Something.Response) {
        let viewModel = Network.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: Network.SomethingElse.Response) {
//        let viewModel = Network.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
