//
//  NetworkRouter.swift
//  LinkedinClone
//
//  Created by MacOS on 17.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NetworkRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol NetworkDataPassing {
    var dataStore: NetworkDataStore? { get }
}

class NetworkRouter: NSObject, NetworkRoutingLogic, NetworkDataPassing {
    weak var viewController: NetworkViewController?
    var dataStore: NetworkDataStore?

}
