//
//  LoginRouter.swift
//  LinkedinClone
//
//  Created by MacOS on 17.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRoutingLogic {
    func routeToHome()
    func routeToSignUp()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    func routeToHome() {
        viewController?.performSegue(withIdentifier: "toTabbar", sender: nil)
    }
    func routeToSignUp(){
    
            let storyBoard = UIStoryboard(name: "Main", bundle: nil)
            let destVC: SignUpViewController = storyBoard.instantiateViewController(identifier: "signUp")
            destVC.modalPresentationStyle = .fullScreen
            viewController?.navigationController?.pushViewController(destVC, animated: true)
        
    }
}
