//
//  LoginWorker.swift
//  LinkedinClone
//
//  Created by MacOS on 17.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol LoginWorkerProtocol: AnyObject{
    func login(email: String , password: String)
}

final class LoginWorker:  LoginWorkerProtocol{
    func login(email: String , password: String){
        
        Auth.auth().signIn(withEmail: email, password: password) {  authData, error in
            
            if error != nil {
                print(error?.localizedDescription)
                Alert.alert(title: "Can not login", message: error!.localizedDescription)
            }else{
                print("succesfully login")
            }
        }
    }
}
