//
//  PublishModels.swift
//  LinkedinClone
//
//  Created by MacOS on 17.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Publish
{
    // MARK: Use cases
    
    enum Publish
    {
        struct Request
        {
            
        }
        
        struct Response
        {
            
        }
        
        struct ViewModel
        {
            
        }
    }
}
