//
//  PublishRouter.swift
//  LinkedinClone
//
//  Created by MacOS on 17.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


import UIKit

protocol PublishRoutingLogic: AnyObject {
    func routeToHome()
}

protocol PublishDataPassing: AnyObject {
    var dataStore: PublishDataStore? { get }
}

class PublishRouter: NSObject, PublishRoutingLogic, PublishDataPassing {
    
    weak var viewController: PublishViewController?
    var dataStore: PublishDataStore?

    func routeToHome() {
        let storyBoard = UIStoryboard(name: "Main", bundle: nil)
        let destVC = storyBoard.instantiateViewController(identifier: "home")
        destVC.modalPresentationStyle = .fullScreen
        viewController?.present(destVC, animated: false, completion: nil)
    }
}
