//
//  PublishPresenter.swift
//  LinkedinClone
//
//  Created by MacOS on 17.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PublishPresentationLogic {
    func alertAction(title: String , message: String , action: UIAlertAction)
    func alert(title: String , message: String)
}

class PublishPresenter: PublishPresentationLogic {
    weak var viewController: PublishDisplayLogic?

    // MARK: Parse and calc respnse from PublishInteractor and send simple view model to PublishViewController to be displayed

    
    
    
    func alertAction(title: String , message: String , action: UIAlertAction) {
        Alert.alertAction(title: title, message: message, action: action)
    }
    
    func alert(title: String , message: String){
        Alert.alert(title: title, message: message)
    }

}
