//
//  SignUpRouter.swift
//  LinkedinClone
//
//  Created by MacOS on 18.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpRoutingLogic: AnyObject {
    func routeToHome()
    func popOver()
  
}

protocol SignUpDataPassing: AnyObject {
    var dataStore: SignUpDataStore? { get }
}

class SignUpRouter: NSObject, SignUpRoutingLogic, SignUpDataPassing {
    weak var viewController: SignUpViewController?
    var dataStore: SignUpDataStore?
    
    func routeToHome() {
        viewController?.performSegue(withIdentifier: "signUpToTabbar", sender: nil)
    }
    func popOver(){
        viewController?.navigationController?.popViewController(animated: true)
    }
   
}

