//
//  SignUpWorker.swift
//  LinkedinClone
//
//  Created by MacOS on 18.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol SignUpWorkerProtocol: AnyObject{
    func createUser(firstName: String , lastName: String ,email: String , password: String , completionBlock: @escaping (_ success: Bool) -> Void)
}

final class SignUpWorker:  SignUpWorkerProtocol{
    func createUser(firstName: String , lastName: String ,email: String , password: String , completionBlock: @escaping (_ success: Bool) -> Void) {
        Auth.auth().createUser(withEmail: email, password: password) {(authResult, error) in
            if (authResult?.user) != nil {
                // save user in fireBase Database
                
                    var ref: DocumentReference? = nil
                    let db = Firestore.firestore()
                    ref = db.collection("users").addDocument(data: [
                        "firstName": "firstName" as String ,
                        "lastName": "lastName" as String,
                        "email": "email" as String
                    ]) { error in
                        if let error = error {
                            
                            print("Error adding document: \(error)")
                        } else {
                            
                            print("Document added with ID: \(ref!.documentID)")
                        }
                    }
                
                completionBlock(true)
                
            } else {
                completionBlock(false)
            }
        }
    }
}
