//
//  SignUpPresenter.swift
//  LinkedinClone
//
//  Created by MacOS on 18.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpPresentationLogic {
    func alert(title: String , message: String)
    func alertAction(title: String , message: String , action: UIAlertAction)
    func presentSomething(response: SignUp.SignUp.Response)
}

class SignUpPresenter: SignUpPresentationLogic {
    weak var viewController: SignUpDisplayLogic?

    // MARK: Parse and calc respnse from SignUpInteractor and send simple view model to SignUpViewController to be displayed

    func presentSomething(response: SignUp.SignUp.Response) {
        let viewModel = SignUp.SignUp.ViewModel()
        viewController?.displaySignUpView(viewModel: viewModel)
    }
    
    
    func alertAction(title: String , message: String , action: UIAlertAction) {
        Alert.alertAction(title: title, message: message, action: action)
    }
    
    func alert(title: String , message: String){
        Alert.alert(title: title, message: message)
    }
}
