//
//  SignUpWorker.swift
//  LinkedinClone
//
//  Created by MacOS on 18.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol SignUpWorkerProtocol: AnyObject{
    func createUser(firstName: String , lastName: String ,email: String , password: String)
}

final class SignUpWorker:  SignUpWorkerProtocol{
    
    func createUser(firstName: String , lastName: String ,email: String , password: String) {
        
        Auth.auth().createUser(withEmail: email, password: password) { (user, error) in
            if let error = error {
                print(error.localizedDescription)
            }
            else{
                
                var ref: DocumentReference? = nil
                let db = Firestore.firestore()
                ref = db.collection("users").addDocument(data: [
                    "firstName": firstName as String ,
                    "lastName": lastName as String
                ]) { err in
                    if let err = err {
                        Alert.alert(title: "Document didn't add", message: error!.localizedDescription)
                        print("Error adding document: \(err)")
                    } else {
                        
                        print("Document added with ID: \(ref!.documentID)")
                    }
                }
            }
        }
    }
}
