//
//  HomeWorker.swift
//  LinkedinClone
//
//  Created by MacOS on 17.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Firebase
import UIKit

protocol HomeWorkerProtocol: AnyObject{
}

final class HomeWorker : HomeWorkerProtocol {
    let db = Firestore.firestore()

    func getData(completion: @escaping ((Result<[Home.Fetch.ViewModel.Post], Error>) -> Void)){
        self.db.collection("posts").getDocuments() {  ( _, result: QuerySnapshot, error
            completion(result)
    }
}
    
   

    
}
