//
//  NotificationsInteractor.swift
//  LinkedinClone
//
//  Created by MacOS on 17.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotificationsBusinessLogic {
    func doSomething(request: Notifications.Something.Request)
//    func doSomethingElse(request: Notifications.SomethingElse.Request)
}

protocol NotificationsDataStore {
    //var name: String { get set }
}

class NotificationsInteractor: NotificationsBusinessLogic, NotificationsDataStore {
    var presenter: NotificationsPresentationLogic?
    var worker: NotificationsWorker?
    //var name: String = ""

    // MARK: Do something (and send response to NotificationsPresenter)

    func doSomething(request: Notifications.Something.Request) {
        worker = NotificationsWorker()
        worker?.doSomeWork()

        let response = Notifications.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: Notifications.SomethingElse.Request) {
//        worker = NotificationsWorker()
//        worker?.doSomeOtherWork()
//
//        let response = Notifications.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
